theme: jekyll-theme-minimal
title: Workshop on Event-Based Vision for Advanced State Estimation and Image Processing - IROS 
show_downloads: false
logo: /images/IROS2025_logo.png
github:
  is_project_page: false
